/* Crear tablespace para el proyecto */
CREATE TABLESPACE TBSGAMARK
DATAFILE 'tbsMARK.dbf'
SIZE 300M;

/* PERMITE EJECUCION DE SCRIPTS DENTRO DEL TABLESPACE CREADO */
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

/* Crear usuario */
CREATE USER gmarket IDENTIFIED BY ORCL1234 
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

/* Asignar los permisos al usuario */
GRANT CREATE SESSION TO gmarket;
GRANT CREATE TABLE TO gmarket;
GRANT CREATE VIEW TO gmarket;
GRANT CREATE PROCEDURE TO gmarket;
GRANT CREATE TRIGGER TO gmarket;
GRANT CREATE SEQUENCE TO gmarket;
GRANT CREATE JOB TO gmarket;